import Head from 'next/head';
import {HeartHandshake,MapPinned,ShieldCheck,Store} from 'lucide-react';
import {CTA,InnerHero,PageShell,SectionHead} from '../components/Site';
const leaders=[
  {img:'/assets/images/founders/nagaraj-nirmala-devi.webp',name:'Nagaraj Nirmala Devi',role:'Founder & Managing Director'},
  {img:'/assets/images/founders/sri-keerthana-devi-c.webp',name:'Sri Keerthana Devi C',role:'Co-Founder & Director'},
];
export default function Founders(){return <PageShell><Head><title>Founders & Leadership | Ecoo Basket B2B</title><meta name='description' content='Meet the founder-led leadership team behind Ecoo Basket B2B Chennai.'/></Head><main>
<InnerHero eyebrow='FOUNDERS & LEADERSHIP' title='Local-market understanding. Founder-led execution.' body='Ecoo Basket is led by a women-led founding team focused on dependable supply relationships, disciplined execution and long-term retail growth from Chennai.' tamil='à®‰à®³à¯à®³à¯‚à®°à¯ à®šà®¨à¯à®¤à¯ˆà®¯à¯ˆ à®ªà¯à®°à®¿à®¨à¯à®¤à¯ à®•à¯Šà®£à¯à®Ÿà¯, à®¨à®®à¯à®ªà®¿à®•à¯à®•à¯ˆà®¯à¯à®Ÿà®©à¯ à®µà®³à®°à¯à®•à®¿à®±à¯‹à®®à¯.' aside={<div className='aside-stat'><b>Women-led</b><span>Founder-driven enterprise</span></div>}/>
<section className='section wrap'><SectionHead eyebrow='THE FOUNDERS' title='Leadership close to the market.' body='Real people, clear accountability and a practical understanding of local retail.'/><div className='leader-grid founders-two'>{leaders.map(l=><article className='leader-card leader-card-photo' key={l.name}><img className='leader-photo' src={l.img} alt={l.name}/><h3>{l.name}</h3><p>{l.role}</p></article>)}</div></section>
<section id='how-we-lead' className='section soft'><div className='wrap'><SectionHead eyebrow='HOW WE LEAD' title='Simple principles that stay useful as we grow.'/><div className='card-grid three'><article className='feature-card'><Store/><h3>Retailer first</h3><p>Availability, clarity, speed and a dependable point of contact.</p></article><article className='feature-card'><ShieldCheck/><h3>Execution over promises</h3><p>Correct orders, transparent coordination and accountable follow-through.</p></article><article className='feature-card'><MapPinned/><h3>Chennai before scale</h3><p>Strengthen local service quality before expanding the operating model.</p></article></div></div></section>
<section className='section wrap'><div className='story-grid'><div><span className='eyebrow'>WHY THIS BUSINESS</span><h2>Neighbourhood retail deserves stronger supply support.</h2><p>Kirana stores and local retailers are deeply connected to the communities they serve. Ecoo Basket is being built to strengthen that connection with practical FMCG sourcing, local coordination and reliable delivery support.</p><p className='tamil dark'>à®‰à®³à¯à®³à¯‚à®°à¯ à®•à®Ÿà¯ˆà®•à®³à®¿à®©à¯ à®µà®³à®°à¯à®šà¯à®šà®¿à®•à¯à®•à¯ à®¨à®®à¯à®ªà®•à®®à®¾à®© à®šà®ªà¯à®³à¯ˆ à®†à®¤à®°à®µà¯ à®…à®µà®šà®¿à®¯à®®à¯.</p></div><div className='principles'><div><HeartHandshake/><b>Human relationships</b><span>Technology supports the relationship; it does not replace it.</span></div><div><ShieldCheck/><b>Operating discipline</b><span>Clear commitments and measurable execution.</span></div><div><MapPinned/><b>Local focus</b><span>Build density and service quality in Chennai first.</span></div></div></div></section>
<CTA title='See the business our founders are building.' body='Explore our B2B FMCG model or place your wholesale order directly on EcooBasket.com.' primary='Order on EcooBasket.com' primaryHref='https://ecoobasket.com' secondary='About the Company' secondaryHref='/company'/></main></PageShell>}

