import Head from 'next/head';
import { ArrowRight, Boxes, Building2, CreditCard, HeartHandshake, MapPin, PackageCheck, ShoppingBasket, Sparkles, Store, Truck } from 'lucide-react';
import { CTA, Metric, PageShell, SectionHead } from '../components/Site';
const heroImage='/assets/images/services/04_Retail_Partner.jpg';
const warehouseImage='/assets/images/warehouse/01_Warehouse_Logistics.jpg';
export default function Home(){return <PageShell><Head>
<title>Ecoo Basket B2B | Chennai FMCG Wholesale & Distribution</title>
<meta name='description' content='Ecoo Basket is a Chennai-focused B2B FMCG wholesale and distribution company serving kirana stores, general trade, mini supermarkets and local businesses.'/>
<link rel='canonical' href='https://ecoobasketb2b.com/'/>
<meta property='og:type' content='website'/>
<meta property='og:title' content='Ecoo Basket B2B | Chennai FMCG Wholesale & Distribution'/>
<meta property='og:description' content='Dependable B2B FMCG supply for Chennai kirana stores and local retail businesses.'/>
<meta property='og:url' content='https://ecoobasketb2b.com/'/>
<meta property='og:image' content='https://ecoobasketb2b.com/assets/images/services/04_Retail_Partner.jpg'/>
<meta name='twitter:card' content='summary_large_image'/>
<meta name='twitter:title' content='Ecoo Basket B2B | Chennai FMCG Wholesale & Distribution'/>
<meta name='twitter:description' content='Dependable B2B FMCG supply for Chennai kirana stores and local retail businesses.'/>
<meta name='twitter:image' content='https://ecoobasketb2b.com/assets/images/services/04_Retail_Partner.jpg'/>
<link rel='icon' href='/assets/images/logo/04_Logo_Icon.jpg'/>
</Head><main>
<section className='hero wrap'><div className='hero-copy'><span className='eyebrow'>CHENNAI B2B FMCG WHOLESALE & DISTRIBUTION</span><h1>Wholesale FMCG supply<br/><span>built for Chennai retailers.</span></h1><p className='lead'>Ecoo Hyper Retail Private Limited supplies kirana stores, general trade, mini supermarkets and food-service businesses with multi-brand FMCG products, local order coordination and dependable Chennai delivery support.</p><p className='hero-tagline'>Stronger supply. Stronger local retail.</p><div className='actions'><a className='btn btn-primary' href='https://www.ecoobasket.com' target='_blank' rel='noreferrer'>Order Now <ArrowRight size={18}/></a><a className='btn btn-ghost' href='/business'>Explore Our Business</a></div><div className='micro-trust'><span><MapPin size={17}/> Chennai only</span><span><CreditCard size={17}/> UPI & Cash on Delivery</span><span><Truck size={17}/> 24â€“48 hour delivery</span></div></div><div className='hero-media'><img src={heroImage} alt='Tamil Nadu neighbourhood kirana store'/><div className='photo-badge'><Store size={22}/><div><b>Retailer first</b><small>Built around real store needs</small></div></div></div></section>
<section className='business-snapshot wrap'><article><span>WHO WE SERVE</span><b>Kirana, general trade & local businesses</b><p>Retailers, mini supermarkets, wholesale outlets and food-service businesses in Chennai.</p></article><article><span>WHAT WE SUPPLY</span><b>Everyday FMCG wholesale categories</b><p>Biscuits, beverages, foods, home care, staples and selected own-brand categories.</p></article><article><span>HOW WE WORK</span><b>Order coordination + local delivery</b><p>Clear product, quantity, price and delivery details before confirmation.</p></article></section>
<section className='metrics wrap'><Metric value='Chennai' label='Current delivery market'/><Metric value='Same day' label='Order dispatch'/><Metric value='24â€“48 hrs' label='Typical delivery window'/><Metric value='â‚¹10,000' label='Minimum wholesale order'/></section>
<section className='site-clarifier wrap'><div className='site-clarifier-copy'><span className='eyebrow'>TWO SITES. TWO CLEAR PURPOSES.</span><h2>Corporate information here. Product ordering there.</h2></div><div className='site-role-card'><span>ECOOBASKETB2B.COM</span><b>Corporate website</b><p>Company, services, kirana support, partnerships, careers and investor information.</p></div><div className='site-role-card order-site'><span>ECOOBASKET.COM</span><b>Wholesale ordering</b><p>Browse products, review current pricing, build your cart and place wholesale orders.</p><a href='https://www.ecoobasket.com' target='_blank' rel='noreferrer'>Open order website <ArrowRight size={16}/></a></div></section>
<section className='section wrap'><SectionHead eyebrow='ABOUT ECOO BASKET' title='Ecoo Basket, in simple terms.' body='A Chennai-focused B2B FMCG wholesale and distribution company built to make everyday retail supply simpler and more dependable.'/><div className='card-grid three'>{[['Chennai B2B FMCG','Wholesale and distribution focused on Chennai retail businesses.'],['Who we serve','Kirana stores, general trade, mini supermarkets and food-service businesses.'],['What we supply','Trusted multi-brand FMCG plus selected Ecoo Nuts & Spices categories.'],['Easy ordering','Place wholesale orders through EcooBasket.com or connect with our team on WhatsApp.'],['Fast local delivery','Same-day dispatch with a typical 24â€“48 hour Chennai delivery window.'],['Clear payment & billing','UPI or Cash on Delivery with GST-compliant invoicing.']].map(([t,d])=><article className='feature-card' key={t}><PackageCheck/><h3>{t}</h3><p>{d}</p></article>)}</div><div className='center-action'><a className='text-link' href='/company'>Know Our Company <ArrowRight size={17}/></a></div></section>
<section className='section soft'><div className='wrap'><div className='product-card-grid'>{[["/assets/images/products/biscuits-snacks.jpg","Biscuits & Snacks","à®ªà®¿à®¸à¯à®•à®Ÿà¯ & à®¸à¯à®©à®¾à®•à¯à®¸à¯"],["/assets/images/products/beverages.jpg","Beverages / Cool Drinks","à®•à¯‚à®²à¯à®Ÿà®¿à®°à®¿à®™à¯à®¸à¯ & à®ªà®¾à®©à®™à¯à®•à®³à¯"],["/assets/images/products/staples.jpg","Foods & Groceries","à®‰à®£à®µà¯ & à®®à®³à®¿à®•à¯ˆ à®ªà¯Šà®°à¯à®Ÿà¯à®•à®³à¯"],["/assets/images/products/home-care.jpg","Home Care","à®µà¯€à®Ÿà¯à®Ÿà¯ à®¤à¯‡à®µà¯ˆà®•à®³à¯"],["/assets/images/products/05_Premium_Dry_Fruits.jpg","Nuts & Dry Fruits","à®¨à®Ÿà¯à®¸à¯ & à®Ÿà¯à®°à¯ˆ à®ƒà®ªà¯à®°à¯‚à®Ÿà¯à®¸à¯"]].map(([img,en,ta],i)=><article className='product-image-card' key={en}><div className='product-image-wrap'><img src={img} alt={en}/><span>0{i+1}</span></div><div className='product-copy'><h3>{en}</h3><b>{ta}</b><p>Wholesale packs Â· Chennai B2B supply</p></div></article>)}</div><div className='center-action'><a className='btn btn-primary' href='https://www.ecoobasket.com' target='_blank' rel='noreferrer'>View Products & Order <ArrowRight size={17}/></a></div></div></section>
<section className='split wrap section'><div className='image-panel'><img src={warehouseImage} alt='Ecoo Basket warehouse and wholesale stock'/><span className='image-tag'>SUPPLY â†’ STORE</span></div><div className='split-copy'><span className='eyebrow'>WAREHOUSE & SUPPLY SUPPORT</span><h2>Reliable warehouse support for Chennai supply.</h2><p>Our stock-handling setup supports faster dispatch, better product readiness and dependable distribution coordination for local retail partners.</p><div className='check-list'><span><PackageCheck/> Organised stock handling</span><span><Boxes/> Multi-category FMCG readiness</span><span><Truck/> Faster dispatch & local delivery support</span></div><a className='text-link' href='/business'>See how our business works <ArrowRight size={17}/></a></div></section>
<section className='section soft'><div className='wrap split'><div className='split-copy'><span className='eyebrow'>OUR STORY</span><h2>Our story begins with local retail.</h2><p>Ecoo Hyper Retail Private Limited was built with a simple belief â€” local retailers deserve a dependable supply partner. Chennai and Tamil Naduâ€™s kirana stores support families, serve neighbourhood needs and keep local commerce moving.</p><p>Our goal is not only to move products, but to strengthen the retail backbone of the community through practical B2B FMCG supply, clear order coordination and reliable delivery support.</p><p className='tamil dark'>à®¤à®®à®¿à®´à¯à®¨à®¾à®Ÿà¯à®Ÿà®¿à®©à¯ à®®à®³à®¿à®•à¯ˆà®•à¯ à®•à®Ÿà¯ˆà®•à®³à¯ à®¨à®®à¯à®ªà®¿à®•à¯à®•à¯ˆà®¯à®¿à®©à¯ à®®à¯ˆà®¯à®™à¯à®•à®³à¯. à®…à®¨à¯à®¤ à®¨à®®à¯à®ªà®¿à®•à¯à®•à¯ˆà®¯à¯ˆ à®µà®²à¯à®ªà¯à®ªà®Ÿà¯à®¤à¯à®¤à¯à®®à¯ à®®à¯Šà®¤à¯à®¤ à®µà®¿à®±à¯à®ªà®©à¯ˆ à®•à¯‚à®Ÿà¯à®Ÿà®¾à®³à®¿à®¯à®¾à®• Ecoo Basket à®šà¯†à®¯à®²à¯à®ªà®Ÿà¯à®•à®¿à®±à®¤à¯.</p><a className='text-link' href='/company'>Read our company story <ArrowRight size={17}/></a></div><div className='image-panel portrait'><img src={heroImage} alt='Tamil Nadu local retail store'/><span className='image-tag'>LOCAL RETAIL Â· TAMIL NADU</span></div></div></section>
<section className='kirana-band'><div className='wrap kirana-inner'><div><span className='eyebrow light'>FOR THE HEART OF EVERY NEIGHBOURHOOD</span><h2>Small stores. An extraordinary role.</h2><p>A kirana store is a familiar face, an essential local service and a livelihood rooted in the community.</p><p className='tamil'>à®¨à®®à¯ à®ªà®•à¯à®¤à®¿à®¯à®¿à®©à¯ à®®à®³à®¿à®•à¯ˆà®•à¯ à®•à®Ÿà¯ˆà®•à®³à¯à®•à¯à®•à®¾à®• â€” à®¨à®®à¯à®ªà®•à®®à®¾à®© à®®à¯Šà®¤à¯à®¤ à®µà®¿à®±à¯à®ªà®©à¯ˆ à®†à®¤à®°à®µà¯.</p></div><a className='btn btn-light' href='/kirana'>Our Kirana Commitment <ArrowRight size={18}/></a></div></section>
<section className='section wrap'><SectionHead eyebrow='FOUNDERS Â· à®Žà®™à¯à®•à®³à¯ à®¨à®¿à®±à¯à®µà®©à®°à¯ à®•à¯à®´à¯' title='Founder-led. Close to the market.' body='A leadership team focused on dependable supply relationships, clear execution and long-term local retail growth.'/><div className='founder-home-grid'><article className='founder-home-card'><img src='/assets/images/founders/nagaraj-nirmala-devi.webp' alt='Nagaraj Nirmala Devi'/><div><span>FOUNDER & MANAGING DIRECTOR</span><h3>Nagaraj Nirmala Devi</h3><p>Leads Ecoo Basket with a focus on dependable supply support and long-term retailer relationships.</p></div></article><article className='founder-home-card'><img src='/assets/images/founders/sri-keerthana-devi-c.webp' alt='Sri Keerthana Devi C'/><div><span>CO-FOUNDER & DIRECTOR</span><h3>Sri Keerthana Devi C</h3><p>Focuses on technology, customer support and clear order coordination to simplify the B2B experience.</p></div></article></div><div className='center-action'><a className='text-link' href='/founders'>Meet Founders & Leadership <ArrowRight size={17}/></a></div></section>
<section className='section wrap'><SectionHead eyebrow='EXPLORE ECOO BASKET' title='Company, founders and growth â€” clearly presented.'/><div className='card-grid three'><a className='feature-card linked' href='/company'><Building2/><h3>About the Company</h3><p>Our story, operating model, legal profile, values and Chennai-first approach.</p></a><a className='feature-card linked' href='/founders'><HeartHandshake/><h3>Founders & Leadership</h3><p>Meet the women-led leadership team and the operating principles behind Ecoo Basket.</p></a><a className='feature-card linked' href='/investors'><Sparkles/><h3>Investor Relations</h3><p>Explore our growth thesis, roadmap and approach to responsible scaling.</p></a></div></section>
<CTA title='Ready for your next wholesale order?' body='Browse products and place your order on EcooBasket.com.' primary='Order Now' primaryHref='https://www.ecoobasket.com' secondary='Talk to Our Team' secondaryHref='/contact'/>
</main></PageShell>}
