import Head from 'next/head';
import {BarChart3,Boxes,Building2,MapPinned,Network,PackageCheck,RefreshCw,ShieldCheck,Store,TimerReset,TrendingUp,Truck,UsersRound,WalletCards} from 'lucide-react';
import {CTA,InnerHero,PageShell,SectionHead} from '../components/Site';

export default function Investors(){return <PageShell><Head>
<title>Invest in Ecoo Basket | Chennai FMCG Distribution Growth</title>
<meta name='description' content='Ecoo Basket is building a Chennai-first B2B FMCG distribution platform with a disciplined city-expansion model and a focus on capital velocity, repeat retail demand and working-capital efficiency.'/>
</Head><main>
<InnerHero eyebrow='INVESTOR RELATIONS' title='Seeking growth capital to build a stronger B2B FMCG distribution business.' body='Ecoo Hyper Retail Private Limited is building a Chennai-first wholesale platform for kirana stores and local retailers. We are open to conversations with strategic and financial investors who can support disciplined, execution-led growth.' aside={<div className='aside-stat'><b>Growth Capital</b><span>Strategic investment discussions</span></div>}/>

<section className='section wrap'><SectionHead eyebrow='COMPANY SNAPSHOT' title='A focused B2B FMCG platform built around local retail.'/><div className='facts-grid'>{[
['Legal entity','Ecoo Hyper Retail Private Limited'],['Headquarters','Vanagaram, Chennai'],['Current market','Chennai'],['Customer focus','Kirana & general trade'],['Business model','Multi-brand FMCG + ECOO Nutzes & ECOO Spizees'],['Digital order channel','EcooBasket.com']
].map(([k,v])=><div className='fact' key={k}><span>{k}</span><b>{v}</b></div>)}</div></section>

<section className='section soft'><div className='wrap'><SectionHead eyebrow='BUSINESS MODEL' title='Three complementary engines: multi-brand FMCG, retail & wholesale sales, and Ecoo-owned brands.' body='Ecoo Basket is designed to combine distribution scale with direct customer access and higher-value own-brand opportunities.'/><div className='card-grid three'>
<article className='feature-card'><Boxes/><h3>Multi-brand FMCG distribution</h3><p>Source and supply a broad range of everyday FMCG products across trusted national and regional brands for kirana stores, general trade and other business customers.</p></article>
<article className='feature-card'><Store/><h3>Retail & wholesale sales channels</h3><p>Serve wholesale B2B demand while also supporting selected retail sales channels, creating multiple routes to market and stronger product movement.</p></article>
<article className='feature-card'><Building2/><h3>Own brands: ECOO Nutzes & ECOO Spizees</h3><p>Develop differentiated Nuts & Dry Fruits and Spices ranges under Ecoo-owned brands, with the potential to strengthen brand equity, category control and long-term margin quality.</p></article>
</div></div></section>

<section className='section wrap'><div className='story-grid'><div><span className='eyebrow'>HOW THE MODEL WORKS</span><h2>Distribution creates reach. Own brands create long-term value.</h2><p>The multi-brand FMCG business builds retailer relationships, order frequency and route density. Retail and wholesale channels expand market access. ECOO Nutzes and ECOO Spizees add a proprietary brand layer that can grow alongside the distribution platform.</p><p>The objective is a balanced model: dependable third-party FMCG distribution for scale, supported by selective own-brand categories for differentiation and value creation.</p></div><div className='principles'>
<div><PackageCheck/><b>Volume engine</b><span>Everyday FMCG demand supports recurring orders and distribution activity.</span></div>
<div><Network/><b>Channel engine</b><span>Wholesale and selected retail routes increase access to customers and product movement.</span></div>
<div><TrendingUp/><b>Brand engine</b><span>Ecoo-owned categories create a path toward stronger differentiation and margin potential.</span></div>
</div></div></section>

<section className='section soft'><div className='wrap'><SectionHead eyebrow='WHY ECOO BASKET' title='A practical opportunity in an essential retail supply chain.' body='Our model is designed around frequent FMCG demand, fragmented local sourcing and the need for dependable last-mile wholesale support.'/><div className='card-grid three'>
<article className='feature-card'><Store/><h3>Large local-retail base</h3><p>Kirana and neighbourhood stores remain important access points for everyday FMCG consumption.</p></article>
<article className='feature-card'><Network/><h3>Fragmented sourcing</h3><p>Retailers often coordinate across multiple suppliers. Better aggregation can reduce sourcing friction and improve replenishment.</p></article>
<article className='feature-card'><TrendingUp/><h3>Repeat-order potential</h3><p>FMCG is a recurring-demand category where service quality, route density and repeat purchasing can strengthen operating efficiency.</p></article>
</div></div></section>

<section className='section soft' id='city-expansion'><div className='wrap'><SectionHead eyebrow='CITY EXPANSION ENGINE' title='Chennai first. Then scale by city-cluster economics.' body='The growth thesis is not to enter every city at once. Ecoo Basket aims to build density, repeat ordering and route economics in one market, then selectively replicate the model across larger and emerging Indian city clusters.'/><div className='growth-grid'><article className='growth-card growth-current'><span>NOW</span><h3>Chennai</h3><p>Current delivery market. Strengthen retailer density, service reliability, assortment and route productivity.</p></article><article className='growth-card'><span>FUTURE STRATEGY</span><h3>Metro & non-metro clusters</h3><p>Evaluate high-demand clusters where distribution density can support efficient replenishment and local fulfilment.</p></article><article className='growth-card'><span>FUTURE STRATEGY</span><h3>Tier-2 cities</h3><p>Target growing consumption markets where fragmented sourcing creates room for organised B2B distribution.</p></article><article className='growth-card'><span>FUTURE STRATEGY</span><h3>Tier-3 cities</h3><p>Assess relationship-led retail markets with strong kirana relevance and underserved supply opportunities.</p></article></div><div className='growth-gates'><b>Expansion gates:</b><span>repeat retailer demand</span><span>service-level consistency</span><span>route density</span><span>inventory rotation</span><span>sustainable unit economics</span></div><p className='growth-note'>These are future strategic markets. Ecoo Basket currently delivers in Chennai.</p></div></section>
<section className='section wrap' id='capital-velocity'><SectionHead eyebrow='VELOCITY OF MONEY' title='Capital velocity & working-capital efficiency.' body='In FMCG distribution, growth is not only about how much capital is raised. It is also about how productively the same rupee can move through inventory, sale, collection and reinvestment while protecting service quality and margin.'/><div className='capital-loop'><article><WalletCards/><b>1. Cash deployed</b><span>Working capital is allocated to fast-moving inventory and fulfilment needs.</span></article><article><Boxes/><b>2. Inventory moves</b><span>Assortment and replenishment discipline aim to reduce avoidable stock holding.</span></article><article><Store/><b>3. Retailer order</b><span>Recurring FMCG demand converts inventory into sales across retailer relationships.</span></article><article><TimerReset/><b>4. Collection</b><span>Shorter, well-managed collection cycles return capital to the operating pool sooner.</span></article><article><RefreshCw/><b>5. Reinvestment</b><span>Recovered capital can be rotated into the next replenishment cycle.</span></article></div><div className='card-grid three velocity-metrics'><article className='feature-card'><BarChart3/><h3>Working Capital Turnover</h3><p><b>Annual Revenue ÷ Average Working Capital</b></p><p>Shows how efficiently working capital supports revenue generation over time.</p></article><article className='feature-card'><RefreshCw/><h3>Inventory Turnover</h3><p><b>Cost of Goods Sold ÷ Average Inventory</b></p><p>Helps track how quickly inventory is moving through the distribution system.</p></article><article className='feature-card'><TimerReset/><h3>Cash Conversion Cycle</h3><p><b>Inventory Days + Receivable Days − Payable Days</b></p><p>Measures how long operating cash is tied up before returning to the business.</p></article></div><div className='capital-principle'><b>Investor principle</b><p>Ecoo Basket’s objective is disciplined capital rotation — faster inventory movement, repeat orders and controlled collection cycles — without sacrificing availability, retailer service or sustainable margins.</p><small>Verified operating figures should be published only after management review and reconciliation with financial records.</small></div></section>
<section className='section wrap'><SectionHead eyebrow='FUNDING PURPOSE' title='Where growth capital can help the business move faster.' body='Investment would be used to strengthen the operating foundation before wider geographic expansion.'/><div className='card-grid three'>
<article className='feature-card'><Boxes/><h3>Inventory depth</h3><p>Improve availability across fast-moving categories and support better retailer fulfilment.</p></article>
<article className='feature-card'><Truck/><h3>Distribution capacity</h3><p>Strengthen warehouse, route planning and local delivery capabilities across Chennai.</p></article>
<article className='feature-card'><PackageCheck/><h3>Supplier & category expansion</h3><p>Deepen multi-brand sourcing relationships and selectively expand high-potential categories.</p></article>
<article className='feature-card'><BarChart3/><h3>Technology & data</h3><p>Improve ordering, retailer insights, sales visibility, route productivity and management reporting.</p></article>
<article className='feature-card'><UsersRound/><h3>Sales execution</h3><p>Build a stronger field team to improve outlet coverage, repeat ordering and retailer relationships.</p></article>
<article className='feature-card'><MapPinned/><h3>Measured market expansion</h3><p>Prove the Chennai model, strengthen unit economics and expand selectively into additional Tamil Nadu markets.</p></article>
</div></section>

<section className='section soft'><div className='wrap'><SectionHead eyebrow='GROWTH ROADMAP' title='Build locally. Prove the model. Scale with discipline.'/><div className='roadmap'>{[
['Phase 01','Strengthen Chennai operations','Improve product availability, ordering discipline, delivery consistency and retailer service.'],
['Phase 02','Increase retail density','Grow repeat orders, route productivity and outlet coverage across Chennai clusters.'],
['Phase 03','Expand categories & partnerships','Deepen supplier relationships and selectively grow own-brand and partner-led opportunities.'],
['Phase 04','Replicate into selected city clusters','After Chennai economics are validated, evaluate selected Tamil Nadu and broader metro, non-metro, Tier-2 and Tier-3 opportunities with the same density-first discipline.']
].map(([p,t,b])=><article key={p}><span>{p}</span><h3>{t}</h3><p>{b}</p></article>)}</div></div></section>

<section className='section wrap'><div className='story-grid'><div><span className='eyebrow'>WHO WE WANT TO SPEAK WITH</span><h2>Investors who can add more than capital.</h2><p>We welcome discussions with investors, family offices, strategic operators, FMCG ecosystem partners and business leaders who understand distribution, retail, supply chain, technology or growth-stage execution.</p><p>We value patient, commercially grounded partners who support strong governance, disciplined use of capital and measurable operating progress.</p></div><div className='principles'>
<div><ShieldCheck/><b>Disciplined governance</b><span>Clear reporting, accountable execution and responsible growth.</span></div>
<div><Building2/><b>Long-term company building</b><span>Focus on durable operating systems rather than growth at any cost.</span></div>
<div><BarChart3/><b>Evidence-led scaling</b><span>Measure service quality, repeat business and operating efficiency before expansion.</span></div>
</div></div></section>

<section className='section soft'><div className='wrap narrow'><SectionHead eyebrow='INVESTMENT CONVERSATION' title='Help us strengthen the next stage of Ecoo Basket.'/><p className='lead-sm'>If you are an investor or strategic partner interested in B2B FMCG distribution, local retail infrastructure and Chennai-first growth, we would be glad to share more about the business, operating plan and capital requirements in a direct conversation.</p><p style={{color:'var(--muted)',fontSize:'13px',marginTop:'20px'}}>This page is for general corporate information and discussion purposes only. It does not constitute a public offer, investment recommendation or promise of returns.</p></div></section>

<CTA title='Interested in supporting the next stage of Ecoo Basket?' body='Start a confidential conversation with our team about the business, growth plan and investment opportunity.' primary='Discuss Investment' primaryHref='/contact' secondary='Explore Our Business' secondaryHref='/business'/>
</main></PageShell>}
