import Head from 'next/head';
import {BadgeIndianRupee,Boxes,Clock3,Handshake,MapPin,PackageCheck,ShoppingBasket,Store,Truck,UsersRound} from 'lucide-react';
import {CTA,InnerHero,PageShell,SectionHead} from '../components/Site';

export default function Kirana(){return <PageShell><Head>
<title>Kirana Stores | Ecoo Basket B2B</title>
<meta name='description' content='Ecoo Basket supports Chennai kirana and grocery stores with practical multi-brand FMCG sourcing, clear wholesale ordering and dependable local delivery support.'/>
</Head><main className='kirana-page'>
<InnerHero eyebrow='கிரானா & மளிகைக் கடைகளுக்காக · FOR KIRANA STORES' title='உங்கள் கடை — உங்கள் பகுதியின் நம்பிக்கை.' body='Kirana retail is built on trust, convenience and everyday availability. Ecoo Basket helps make FMCG sourcing simpler, clearer and more dependable.' tamil='கடைக்காரர் மொத்த சந்தைக்கு அடிக்கடி செல்ல வேண்டிய நேரத்தை குறைத்து, கடை மற்றும் வாடிக்கையாளர்களில் அதிக கவனம் செலுத்த உதவும் B2B wholesale supply support.' />

<section className='section wrap split'><div className='image-panel portrait'><img src='/assets/images/services/04_Retail_Partner.jpg' alt='Tamil Nadu kirana store'/><span className='image-tag'>LOCAL RETAIL · TAMIL NADU</span></div><div className='split-copy'><span className='eyebrow'>இந்தியாவின் உள்ளூர் சில்லறை வணிகத்தின் முதுகெலும்பு · LOCAL RETAIL BACKBONE</span><h2>ஒரு மளிகைக் கடை என்பது விற்பனை செய்யும் இடம் மட்டும் அல்ல.</h2><p className='tamil dark'>மளிகைக் கடைகள் குடும்பங்களின் அன்றாட தேவைகளை அருகிலேயே பூர்த்தி செய்கின்றன. வாடிக்கையாளர்களின் வாங்கும் பழக்கம், விருப்பமான பிராண்டுகள், வேகமாக விற்கும் பொருட்கள் ஆகியவற்றை கடைக்காரர் நெருக்கமாக அறிந்திருப்பார்.</p><p>Across India, kirana stores are trusted neighbourhood businesses built on familiarity, convenience and long-term customer relationships.</p></div></section>

<section className='section soft'><div className='wrap'><SectionHead eyebrow='கடைக்காரரின் தினசரி சவால் · THE REAL SOURCING PROBLEM' title='மொத்த சந்தைக்கு செல்லும் நேரமும் ஒரு business cost தான்.' body='Different brands, pack sizes and stock availability can force a retailer to visit multiple wholesale points. Travel, waiting and follow-up take valuable time away from the store.'/><div className='card-grid three'>
<article className='feature-card'><Clock3/><h3>நேர இழப்பு · Time lost in sourcing</h3><p className='tamil'>தேவையான பொருட்களுக்கு இரண்டு அல்லது மூன்று இடங்களைச் சுற்ற வேண்டியிருந்தால், வாடிக்கையாளர்களை கவனிக்கும் நேரம் குறைகிறது.</p><p className='en-support'>Repeated sourcing trips reduce the time available for customers and store operations.</p></article>
<article className='feature-card'><BadgeIndianRupee/><h3>முதலீடு முடக்கம் · Working capital pressure</h3><p className='tamil'>ஒவ்வொரு பொருளுக்கும் ஒரே அளவு தேவை இருக்காது. அதிகமாக வாங்கினால் பணமும் shelf space-மும் மெதுவாக விற்கும் stock-ல் முடங்கிவிடலாம்.</p><p className='en-support'>Better quantity planning helps reduce slow-moving stock and unnecessary cash blockage.</p></article>
<article className='feature-card'><PackageCheck/><h3>Stock கிடைப்பதில் சிக்கல் · Availability gaps</h3><p className='tamil'>வேகமாக விற்கும் பொருள் stock-out ஆனால், வாடிக்கையாளர் வேறு கடைக்குச் செல்ல வாய்ப்பு உள்ளது.</p><p className='en-support'>Reliable replenishment helps keep fast-moving products available when customers need them.</p></article>
</div></div></section>
<section className='section wrap'><SectionHead eyebrow='ஒரே இடத்தில் MULTI-BRAND SUPPLY' title='பல பிராண்டுகள். பல categories. ஒரு தெளிவான wholesale relationship.' body='Ecoo Basket helps reduce sourcing complexity by coordinating product, quantity, rate, availability and delivery details through one business relationship.'/><div className='support-table'>
<div><ShoppingBasket/><b>பல category-கள் · Multi-category basket</b><span>Biscuits, beverages, foods, home care, staples மற்றும் selected FMCG categories-ஐ ஒரே order planning-ல் பார்க்கலாம்.</span></div>
<div><Boxes/><b>தேவைக்கேற்ற quantity · Demand-based planning</b><span>கடையின் விற்பனை வேகத்துக்கு ஏற்ற pack quantity மற்றும் available options-ஐ தெளிவாக review செய்யலாம்.</span></div>
<div><Handshake/><b>ஒரே business contact · One accountable contact</b><span>பல suppliers-ஐ தனித்தனியாக follow-up செய்வதை குறைத்து, ஒரு clear contact மூலம் coordination பெறலாம்.</span></div>
<div><Truck/><b>Chennai delivery support</b><span>Serviceability மற்றும் delivery schedule-ஐ order confirmation-க்கு முன்பே தெளிவாக அறிந்து கொள்ளலாம்.</span></div>
</div></section>

<section className='section soft'><div className='wrap'><SectionHead eyebrow='டிஜிட்டல் சந்தையில் உள்ளூர் வணிகம் · LOCAL RETAIL IN A DIGITAL MARKET' title='E-commerce வளர்ந்தாலும், neighbourhood trust-க்கு தனி மதிப்பு உள்ளது.' body='Customers expect choice, convenience and clear pricing. Kirana stores can stay strong by combining trusted local relationships with better sourcing and faster replenishment.'/><div className='card-grid three'>
<article className='feature-card'><UsersRound/><h3>வாடிக்கையாளர் நம்பிக்கை · Customer trust</h3><p className='tamil'>பழக்கமான கடை, அறிமுகமான முகம், உடனடி உதவி — இவை local kirana store-ன் மிகப்பெரிய பலம்.</p><p className='en-support'>Personal relationships remain a powerful advantage for neighbourhood retail.</p></article>
<article className='feature-card'><Store/><h3>கடையில் அதிக நேரம் · More time in the store</h3><p className='tamil'>மொத்த சந்தைக்கு செல்லும் நேரம் குறைந்தால், customer service, selling, shelf management ஆகியவற்றில் அதிக கவனம் செலுத்த முடியும்.</p><p className='en-support'>Less sourcing time means more time for customers, merchandising and store growth.</p></article>
<article className='feature-card'><MapPin/><h3>அருகாமை சேவை · Local convenience</h3><p className='tamil'>வீட்டிற்கு அருகிலேயே தேவையான பொருள், வேகமான வாங்குதல், நம்பகமான சேவை — இவை kirana retail-ன் நடைமுறை பலங்கள்.</p><p className='en-support'>Nearby availability and familiar service remain strong reasons to shop local.</p></article>
</div></div></section>

<section className='section wrap'><div className='story-grid'><div><span className='eyebrow'>ECOO BASKET COMMITMENT</span><h2>கடைக்காரர் supply-ஐ தேடி ஓடாமல், business வளர்ச்சியில் கவனம் செலுத்த வேண்டும்.</h2><p className='tamil dark'>Retailer-ஐ replace செய்வது எங்கள் நோக்கம் அல்ல. Retailer-ஐ stronger ஆக்குவதுதான் எங்கள் நோக்கம் — தெளிவான sourcing, dependable order coordination மற்றும் local FMCG supply support மூலம்.</p><p>Our role is to strengthen neighbourhood retailers with a simpler, more dependable supply experience.</p></div><div className='principles'>
<div><Handshake/><b>பரிவர்த்தனைக்கு முன் நம்பிக்கை · Trust before transactions</b><span>Long-term retailer relationships, clear communication and accountable support.</span></div>
<div><PackageCheck/><b>சரியான stock planning · Right stock, clearer planning</b><span>Availability and quantity information before order confirmation.</span></div>
<div><Truck/><b>கடையை ஆதரிக்கும் supply · Supply that supports the store</b><span>Reduce avoidable sourcing effort and keep the retailer focused on local customers.</span></div>
</div></div></section>
<section className='kirana-band'><div className='wrap kirana-inner'><div><span className='eyebrow light'>மளிகைக் கடைகளின் வளர்ச்சிக்காக · BUILT FOR LOCAL RETAIL</span><h2>Stronger supply. More time in your store.</h2><p className='tamil'>பல இடங்களில் பொருட்களைத் தேடுவதற்குப் பதிலாக, உங்கள் கடை, உங்கள் வாடிக்கையாளர்கள் மற்றும் உங்கள் விற்பனை வளர்ச்சியில் கவனம் செலுத்த உதவும் B2B supply partner.</p></div><a className='btn btn-light' href='https://www.ecoobasket.com' target='_blank' rel='noreferrer'>Products பார்க்க & Order செய்ய</a></div></section>
<CTA title='Keep your shelves ready for the next customer.' body='Place your wholesale order through EcooBasket.com or speak with our Chennai team.' primary='Order Now' primaryHref='https://www.ecoobasket.com' secondary='Contact Support' secondaryHref='/contact'/>
</main></PageShell>}
