import Head from 'next/head';
import {BadgeIndianRupee,Clock3,Handshake,PackageCheck,Store,Truck} from 'lucide-react';
import {CTA,InnerHero,PageShell,SectionHead} from '../components/Site';
export default function Kirana(){return <PageShell><Head><title>Kirana Stores | Ecoo Basket B2B</title><meta name='description' content='Ecoo Basket supports Chennai kirana and grocery stores with clear wholesale ordering and dependable FMCG delivery support.'/></Head><main>
<InnerHero eyebrow='கிரானா & மளிகை கடைகளுக்காக · FOR KIRANA STORES' title='உங்கள் கடைக்கு நம்பகமான wholesale supply partner.' body='Neighbourhood retail runs on trust, availability and speed. Ecoo Basket makes FMCG sourcing, ordering and Chennai delivery easier to manage.' tamil='மளிகை கடைகளுக்கு தேவையான பொருட்கள், தெளிவான விலை, எளிய ஆர்டர் மற்றும் நம்பகமான டெலிவரி ஆதரவு.' />
<section className='section wrap split'><div className='image-panel portrait'><img src='/assets/images/services/04_Retail_Partner.jpg' alt='Tamil Nadu kirana store'/><span className='image-tag'>LOCAL RETAIL · TAMIL NADU</span></div><div className='split-copy'><span className='eyebrow'>மளிகை கடையின் முக்கியத்துவம் · THE KIRANA STORY</span><h2>ஒரு கடை மட்டும் அல்ல. உங்கள் பகுதியின் நம்பிக்கை.</h2><p>மளிகை கடைகள் அன்றாட தேவைகளை வீட்டுக்கு அருகில் கொண்டு சேர்க்கின்றன. குடும்பங்கள், neighbourhood customers மற்றும் local economy-க்கு அவை முக்கியமான பங்கு வகிக்கின்றன.</p><p>Kirana stores build customer relationships that large formats cannot easily replicate. Our role is to make the supply side simpler and more dependable.</p></div></section>
<section className='section soft'><div className='wrap'><SectionHead eyebrow='கடைகள் சந்திக்கும் சவால்கள் · COMMON CHALLENGES' title='Supply problem குறைந்தால், sales focus அதிகரிக்கும்.' body='Everyday retail needs predictable stock, clear rates and reliable fulfilment.'/><div className='card-grid three'><article className='feature-card'><Clock3/><h3>டெலிவரி நேரம் தெளிவில்லாமை</h3><p>Unclear fulfilment makes stock planning difficult.</p></article><article className='feature-card'><BadgeIndianRupee/><h3>விலை & terms குழப்பம்</h3><p>Box rate, quantity and payment terms தெளிவாக இருக்க வேண்டும்.</p></article><article className='feature-card'><PackageCheck/><h3>Fast-moving stock கிடைக்காமை</h3><p>Core products easy-ஆ reorder செய்ய முடிவது முக்கியம்.</p></article></div></div></section>
<section className='section wrap'><SectionHead eyebrow='ECOO BASKET SUPPORT' title='Simple support. Clear business process.' body='கடைக்காரர் easy-ஆ புரிந்து கொள்ளும் straightforward wholesale support.'/><div className='support-table'><div><Handshake/><b>ஒரே business contact</b><span>Need help? Talk to a real person.</span></div><div><PackageCheck/><b>Clear order coordination</b><span>Products, quantity, rate and terms முன்பே confirm.</span></div><div><Truck/><b>Chennai delivery support</b><span>Serviceability மற்றும் delivery schedule முன்பே தெளிவு.</span></div><div><Store/><b>Easy repeat ordering</b><span>EcooBasket.com மூலம் மீண்டும் order place செய்யலாம்.</span></div></div></section>
<section className='kirana-band'><div className='wrap kirana-inner'><div><span className='eyebrow light'>மளிகை கடைகளின் வளர்ச்சிக்காக</span><h2>Right products. Clear ordering. Reliable support.</h2><p className='tamil'>உங்கள் கடை shelves ready-ஆ இருக்க, wholesale supply process simple-ஆ இருக்க வேண்டும்.</p></div><a className='btn btn-light' href='https://ecoobasket.com' target='_blank' rel='noreferrer'>இப்போ Order செய்யுங்கள்</a></div></section>
<CTA title='Keep your shelves ready for the next customer.' body='Place your wholesale order through EcooBasket.com or speak with our Chennai team.' primary='Order Now' primaryHref='https://ecoobasket.com' secondary='Contact Support' secondaryHref='/contact'/></main></PageShell>}
