import Head from 'next/head';
import {BadgeIndianRupee,Boxes,Clock3,Handshake,MapPin,PackageCheck,ShoppingBasket,Store,Truck,UsersRound} from 'lucide-react';
import {CTA,InnerHero,PageShell,SectionHead} from '../components/Site';

export default function Kirana(){return <PageShell><Head>
<title>Kirana Stores | Ecoo Basket B2B</title>
<meta name='description' content='Ecoo Basket supports Chennai kirana and grocery stores with practical multi-brand FMCG sourcing, clear wholesale ordering and dependable local delivery support.'/>
</Head><main className='kirana-page'>
<InnerHero eyebrow='à®•à®¿à®°à®¾à®©à®¾ & à®®à®³à®¿à®•à¯ˆà®•à¯ à®•à®Ÿà¯ˆà®•à®³à¯à®•à¯à®•à®¾à®• Â· FOR KIRANA STORES' title='à®‰à®™à¯à®•à®³à¯ à®•à®Ÿà¯ˆ â€” à®‰à®™à¯à®•à®³à¯ à®ªà®•à¯à®¤à®¿à®¯à®¿à®©à¯ à®¨à®®à¯à®ªà®¿à®•à¯à®•à¯ˆ.' body='Kirana retail is built on trust, convenience and everyday availability. Ecoo Basket helps make FMCG sourcing simpler, clearer and more dependable.' tamil='à®•à®Ÿà¯ˆà®•à¯à®•à®¾à®°à®°à¯ à®®à¯Šà®¤à¯à®¤ à®šà®¨à¯à®¤à¯ˆà®•à¯à®•à¯ à®…à®Ÿà®¿à®•à¯à®•à®Ÿà®¿ à®šà¯†à®²à¯à®² à®µà¯‡à®£à¯à®Ÿà®¿à®¯ à®¨à¯‡à®°à®¤à¯à®¤à¯ˆ à®•à¯à®±à¯ˆà®¤à¯à®¤à¯, à®•à®Ÿà¯ˆ à®®à®±à¯à®±à¯à®®à¯ à®µà®¾à®Ÿà®¿à®•à¯à®•à¯ˆà®¯à®¾à®³à®°à¯à®•à®³à®¿à®²à¯ à®…à®¤à®¿à®• à®•à®µà®©à®®à¯ à®šà¯†à®²à¯à®¤à¯à®¤ à®‰à®¤à®µà¯à®®à¯ B2B wholesale supply support.' />

<section className='section wrap split'><div className='image-panel portrait'><img src='/assets/images/services/04_Retail_Partner.jpg' alt='Tamil Nadu kirana store'/><span className='image-tag'>LOCAL RETAIL Â· TAMIL NADU</span></div><div className='split-copy'><span className='eyebrow'>à®‡à®¨à¯à®¤à®¿à®¯à®¾à®µà®¿à®©à¯ à®‰à®³à¯à®³à¯‚à®°à¯ à®šà®¿à®²à¯à®²à®±à¯ˆ à®µà®£à®¿à®•à®¤à¯à®¤à®¿à®©à¯ à®®à¯à®¤à¯à®•à¯†à®²à¯à®®à¯à®ªà¯ Â· LOCAL RETAIL BACKBONE</span><h2>à®’à®°à¯ à®®à®³à®¿à®•à¯ˆà®•à¯ à®•à®Ÿà¯ˆ à®Žà®©à¯à®ªà®¤à¯ à®µà®¿à®±à¯à®ªà®©à¯ˆ à®šà¯†à®¯à¯à®¯à¯à®®à¯ à®‡à®Ÿà®®à¯ à®®à®Ÿà¯à®Ÿà¯à®®à¯ à®…à®²à¯à®².</h2><p className='tamil dark'>à®®à®³à®¿à®•à¯ˆà®•à¯ à®•à®Ÿà¯ˆà®•à®³à¯ à®•à¯à®Ÿà¯à®®à¯à®ªà®™à¯à®•à®³à®¿à®©à¯ à®…à®©à¯à®±à®¾à®Ÿ à®¤à¯‡à®µà¯ˆà®•à®³à¯ˆ à®…à®°à¯à®•à®¿à®²à¯‡à®¯à¯‡ à®ªà¯‚à®°à¯à®¤à¯à®¤à®¿ à®šà¯†à®¯à¯à®•à®¿à®©à¯à®±à®©. à®µà®¾à®Ÿà®¿à®•à¯à®•à¯ˆà®¯à®¾à®³à®°à¯à®•à®³à®¿à®©à¯ à®µà®¾à®™à¯à®•à¯à®®à¯ à®ªà®´à®•à¯à®•à®®à¯, à®µà®¿à®°à¯à®ªà¯à®ªà®®à®¾à®© à®ªà®¿à®°à®¾à®£à¯à®Ÿà¯à®•à®³à¯, à®µà¯‡à®•à®®à®¾à®• à®µà®¿à®±à¯à®•à¯à®®à¯ à®ªà¯Šà®°à¯à®Ÿà¯à®•à®³à¯ à®†à®•à®¿à®¯à®µà®±à¯à®±à¯ˆ à®•à®Ÿà¯ˆà®•à¯à®•à®¾à®°à®°à¯ à®¨à¯†à®°à¯à®•à¯à®•à®®à®¾à®• à®…à®±à®¿à®¨à¯à®¤à®¿à®°à¯à®ªà¯à®ªà®¾à®°à¯.</p><p>Across India, kirana stores are trusted neighbourhood businesses built on familiarity, convenience and long-term customer relationships.</p></div></section>

<section className='section soft'><div className='wrap'><SectionHead eyebrow='à®•à®Ÿà¯ˆà®•à¯à®•à®¾à®°à®°à®¿à®©à¯ à®¤à®¿à®©à®šà®°à®¿ à®šà®µà®¾à®²à¯ Â· THE REAL SOURCING PROBLEM' title='à®®à¯Šà®¤à¯à®¤ à®šà®¨à¯à®¤à¯ˆà®•à¯à®•à¯ à®šà¯†à®²à¯à®²à¯à®®à¯ à®¨à¯‡à®°à®®à¯à®®à¯ à®’à®°à¯ business cost à®¤à®¾à®©à¯.' body='Different brands, pack sizes and stock availability can force a retailer to visit multiple wholesale points. Travel, waiting and follow-up take valuable time away from the store.'/><div className='card-grid three'>
<article className='feature-card'><Clock3/><h3>à®¨à¯‡à®° à®‡à®´à®ªà¯à®ªà¯ Â· Time lost in sourcing</h3><p className='tamil'>à®¤à¯‡à®µà¯ˆà®¯à®¾à®© à®ªà¯Šà®°à¯à®Ÿà¯à®•à®³à¯à®•à¯à®•à¯ à®‡à®°à®£à¯à®Ÿà¯ à®…à®²à¯à®²à®¤à¯ à®®à¯‚à®©à¯à®±à¯ à®‡à®Ÿà®™à¯à®•à®³à¯ˆà®šà¯ à®šà¯à®±à¯à®± à®µà¯‡à®£à¯à®Ÿà®¿à®¯à®¿à®°à¯à®¨à¯à®¤à®¾à®²à¯, à®µà®¾à®Ÿà®¿à®•à¯à®•à¯ˆà®¯à®¾à®³à®°à¯à®•à®³à¯ˆ à®•à®µà®©à®¿à®•à¯à®•à¯à®®à¯ à®¨à¯‡à®°à®®à¯ à®•à¯à®±à¯ˆà®•à®¿à®±à®¤à¯.</p><p className='en-support'>Repeated sourcing trips reduce the time available for customers and store operations.</p></article>
<article className='feature-card'><BadgeIndianRupee/><h3>à®®à¯à®¤à®²à¯€à®Ÿà¯ à®®à¯à®Ÿà®•à¯à®•à®®à¯ Â· Working capital pressure</h3><p className='tamil'>à®’à®µà¯à®µà¯Šà®°à¯ à®ªà¯Šà®°à¯à®³à¯à®•à¯à®•à¯à®®à¯ à®’à®°à¯‡ à®…à®³à®µà¯ à®¤à¯‡à®µà¯ˆ à®‡à®°à¯à®•à¯à®•à®¾à®¤à¯. à®…à®¤à®¿à®•à®®à®¾à®• à®µà®¾à®™à¯à®•à®¿à®©à®¾à®²à¯ à®ªà®£à®®à¯à®®à¯ shelf space-à®®à¯à®®à¯ à®®à¯†à®¤à¯à®µà®¾à®• à®µà®¿à®±à¯à®•à¯à®®à¯ stock-à®²à¯ à®®à¯à®Ÿà®™à¯à®•à®¿à®µà®¿à®Ÿà®²à®¾à®®à¯.</p><p className='en-support'>Better quantity planning helps reduce slow-moving stock and unnecessary cash blockage.</p></article>
<article className='feature-card'><PackageCheck/><h3>Stock à®•à®¿à®Ÿà¯ˆà®ªà¯à®ªà®¤à®¿à®²à¯ à®šà®¿à®•à¯à®•à®²à¯ Â· Availability gaps</h3><p className='tamil'>à®µà¯‡à®•à®®à®¾à®• à®µà®¿à®±à¯à®•à¯à®®à¯ à®ªà¯Šà®°à¯à®³à¯ stock-out à®†à®©à®¾à®²à¯, à®µà®¾à®Ÿà®¿à®•à¯à®•à¯ˆà®¯à®¾à®³à®°à¯ à®µà¯‡à®±à¯ à®•à®Ÿà¯ˆà®•à¯à®•à¯à®šà¯ à®šà¯†à®²à¯à®² à®µà®¾à®¯à¯à®ªà¯à®ªà¯ à®‰à®³à¯à®³à®¤à¯.</p><p className='en-support'>Reliable replenishment helps keep fast-moving products available when customers need them.</p></article>
</div></div></section>
<section className='section wrap'><SectionHead eyebrow='à®’à®°à¯‡ à®‡à®Ÿà®¤à¯à®¤à®¿à®²à¯ MULTI-BRAND SUPPLY' title='à®ªà®² à®ªà®¿à®°à®¾à®£à¯à®Ÿà¯à®•à®³à¯. à®ªà®² categories. à®’à®°à¯ à®¤à¯†à®³à®¿à®µà®¾à®© wholesale relationship.' body='Ecoo Basket helps reduce sourcing complexity by coordinating product, quantity, rate, availability and delivery details through one business relationship.'/><div className='support-table'>
<div><ShoppingBasket/><b>à®ªà®² category-à®•à®³à¯ Â· Multi-category basket</b><span>Biscuits, beverages, foods, home care, staples à®®à®±à¯à®±à¯à®®à¯ selected FMCG categories-à® à®’à®°à¯‡ order planning-à®²à¯ à®ªà®¾à®°à¯à®•à¯à®•à®²à®¾à®®à¯.</span></div>
<div><Boxes/><b>à®¤à¯‡à®µà¯ˆà®•à¯à®•à¯‡à®±à¯à®± quantity Â· Demand-based planning</b><span>à®•à®Ÿà¯ˆà®¯à®¿à®©à¯ à®µà®¿à®±à¯à®ªà®©à¯ˆ à®µà¯‡à®•à®¤à¯à®¤à¯à®•à¯à®•à¯ à®à®±à¯à®± pack quantity à®®à®±à¯à®±à¯à®®à¯ available options-à® à®¤à¯†à®³à®¿à®µà®¾à®• review à®šà¯†à®¯à¯à®¯à®²à®¾à®®à¯.</span></div>
<div><Handshake/><b>à®’à®°à¯‡ business contact Â· One accountable contact</b><span>à®ªà®² suppliers-à® à®¤à®©à®¿à®¤à¯à®¤à®©à®¿à®¯à®¾à®• follow-up à®šà¯†à®¯à¯à®µà®¤à¯ˆ à®•à¯à®±à¯ˆà®¤à¯à®¤à¯, à®’à®°à¯ clear contact à®®à¯‚à®²à®®à¯ coordination à®ªà¯†à®±à®²à®¾à®®à¯.</span></div>
<div><Truck/><b>Chennai delivery support</b><span>Serviceability à®®à®±à¯à®±à¯à®®à¯ delivery schedule-à® order confirmation-à®•à¯à®•à¯ à®®à¯à®©à¯à®ªà¯‡ à®¤à¯†à®³à®¿à®µà®¾à®• à®…à®±à®¿à®¨à¯à®¤à¯ à®•à¯Šà®³à¯à®³à®²à®¾à®®à¯.</span></div>
</div></section>

<section className='section soft'><div className='wrap'><SectionHead eyebrow='à®Ÿà®¿à®œà®¿à®Ÿà¯à®Ÿà®²à¯ à®šà®¨à¯à®¤à¯ˆà®¯à®¿à®²à¯ à®‰à®³à¯à®³à¯‚à®°à¯ à®µà®£à®¿à®•à®®à¯ Â· LOCAL RETAIL IN A DIGITAL MARKET' title='E-commerce à®µà®³à®°à¯à®¨à¯à®¤à®¾à®²à¯à®®à¯, neighbourhood trust-à®•à¯à®•à¯ à®¤à®©à®¿ à®®à®¤à®¿à®ªà¯à®ªà¯ à®‰à®³à¯à®³à®¤à¯.' body='Customers expect choice, convenience and clear pricing. Kirana stores can stay strong by combining trusted local relationships with better sourcing and faster replenishment.'/><div className='card-grid three'>
<article className='feature-card'><UsersRound/><h3>à®µà®¾à®Ÿà®¿à®•à¯à®•à¯ˆà®¯à®¾à®³à®°à¯ à®¨à®®à¯à®ªà®¿à®•à¯à®•à¯ˆ Â· Customer trust</h3><p className='tamil'>à®ªà®´à®•à¯à®•à®®à®¾à®© à®•à®Ÿà¯ˆ, à®…à®±à®¿à®®à¯à®•à®®à®¾à®© à®®à¯à®•à®®à¯, à®‰à®Ÿà®©à®Ÿà®¿ à®‰à®¤à®µà®¿ â€” à®‡à®µà¯ˆ local kirana store-à®©à¯ à®®à®¿à®•à®ªà¯à®ªà¯†à®°à®¿à®¯ à®ªà®²à®®à¯.</p><p className='en-support'>Personal relationships remain a powerful advantage for neighbourhood retail.</p></article>
<article className='feature-card'><Store/><h3>à®•à®Ÿà¯ˆà®¯à®¿à®²à¯ à®…à®¤à®¿à®• à®¨à¯‡à®°à®®à¯ Â· More time in the store</h3><p className='tamil'>à®®à¯Šà®¤à¯à®¤ à®šà®¨à¯à®¤à¯ˆà®•à¯à®•à¯ à®šà¯†à®²à¯à®²à¯à®®à¯ à®¨à¯‡à®°à®®à¯ à®•à¯à®±à¯ˆà®¨à¯à®¤à®¾à®²à¯, customer service, selling, shelf management à®†à®•à®¿à®¯à®µà®±à¯à®±à®¿à®²à¯ à®…à®¤à®¿à®• à®•à®µà®©à®®à¯ à®šà¯†à®²à¯à®¤à¯à®¤ à®®à¯à®Ÿà®¿à®¯à¯à®®à¯.</p><p className='en-support'>Less sourcing time means more time for customers, merchandising and store growth.</p></article>
<article className='feature-card'><MapPin/><h3>à®…à®°à¯à®•à®¾à®®à¯ˆ à®šà¯‡à®µà¯ˆ Â· Local convenience</h3><p className='tamil'>à®µà¯€à®Ÿà¯à®Ÿà®¿à®±à¯à®•à¯ à®…à®°à¯à®•à®¿à®²à¯‡à®¯à¯‡ à®¤à¯‡à®µà¯ˆà®¯à®¾à®© à®ªà¯Šà®°à¯à®³à¯, à®µà¯‡à®•à®®à®¾à®© à®µà®¾à®™à¯à®•à¯à®¤à®²à¯, à®¨à®®à¯à®ªà®•à®®à®¾à®© à®šà¯‡à®µà¯ˆ â€” à®‡à®µà¯ˆ kirana retail-à®©à¯ à®¨à®Ÿà¯ˆà®®à¯à®±à¯ˆ à®ªà®²à®™à¯à®•à®³à¯.</p><p className='en-support'>Nearby availability and familiar service remain strong reasons to shop local.</p></article>
</div></div></section>

<section className='section wrap'><div className='story-grid'><div><span className='eyebrow'>ECOO BASKET COMMITMENT</span><h2>à®•à®Ÿà¯ˆà®•à¯à®•à®¾à®°à®°à¯ supply-à® à®¤à¯‡à®Ÿà®¿ à®“à®Ÿà®¾à®®à®²à¯, business à®µà®³à®°à¯à®šà¯à®šà®¿à®¯à®¿à®²à¯ à®•à®µà®©à®®à¯ à®šà¯†à®²à¯à®¤à¯à®¤ à®µà¯‡à®£à¯à®Ÿà¯à®®à¯.</h2><p className='tamil dark'>Retailer-à® replace à®šà¯†à®¯à¯à®µà®¤à¯ à®Žà®™à¯à®•à®³à¯ à®¨à¯‹à®•à¯à®•à®®à¯ à®…à®²à¯à®². Retailer-à® stronger à®†à®•à¯à®•à¯à®µà®¤à¯à®¤à®¾à®©à¯ à®Žà®™à¯à®•à®³à¯ à®¨à¯‹à®•à¯à®•à®®à¯ â€” à®¤à¯†à®³à®¿à®µà®¾à®© sourcing, dependable order coordination à®®à®±à¯à®±à¯à®®à¯ local FMCG supply support à®®à¯‚à®²à®®à¯.</p><p>Our role is to strengthen neighbourhood retailers with a simpler, more dependable supply experience.</p></div><div className='principles'>
<div><Handshake/><b>à®ªà®°à®¿à®µà®°à¯à®¤à¯à®¤à®©à¯ˆà®•à¯à®•à¯ à®®à¯à®©à¯ à®¨à®®à¯à®ªà®¿à®•à¯à®•à¯ˆ Â· Trust before transactions</b><span>Long-term retailer relationships, clear communication and accountable support.</span></div>
<div><PackageCheck/><b>à®šà®°à®¿à®¯à®¾à®© stock planning Â· Right stock, clearer planning</b><span>Availability and quantity information before order confirmation.</span></div>
<div><Truck/><b>à®•à®Ÿà¯ˆà®¯à¯ˆ à®†à®¤à®°à®¿à®•à¯à®•à¯à®®à¯ supply Â· Supply that supports the store</b><span>Reduce avoidable sourcing effort and keep the retailer focused on local customers.</span></div>
</div></div></section>
<section className='kirana-band'><div className='wrap kirana-inner'><div><span className='eyebrow light'>à®®à®³à®¿à®•à¯ˆà®•à¯ à®•à®Ÿà¯ˆà®•à®³à®¿à®©à¯ à®µà®³à®°à¯à®šà¯à®šà®¿à®•à¯à®•à®¾à®• Â· BUILT FOR LOCAL RETAIL</span><h2>Stronger supply. More time in your store.</h2><p className='tamil'>à®ªà®² à®‡à®Ÿà®™à¯à®•à®³à®¿à®²à¯ à®ªà¯Šà®°à¯à®Ÿà¯à®•à®³à¯ˆà®¤à¯ à®¤à¯‡à®Ÿà¯à®µà®¤à®±à¯à®•à¯à®ªà¯ à®ªà®¤à®¿à®²à®¾à®•, à®‰à®™à¯à®•à®³à¯ à®•à®Ÿà¯ˆ, à®‰à®™à¯à®•à®³à¯ à®µà®¾à®Ÿà®¿à®•à¯à®•à¯ˆà®¯à®¾à®³à®°à¯à®•à®³à¯ à®®à®±à¯à®±à¯à®®à¯ à®‰à®™à¯à®•à®³à¯ à®µà®¿à®±à¯à®ªà®©à¯ˆ à®µà®³à®°à¯à®šà¯à®šà®¿à®¯à®¿à®²à¯ à®•à®µà®©à®®à¯ à®šà¯†à®²à¯à®¤à¯à®¤ à®‰à®¤à®µà¯à®®à¯ B2B supply partner.</p></div><a className='btn btn-light' href='https://www.ecoobasket.com' target='_blank' rel='noreferrer'>Products à®ªà®¾à®°à¯à®•à¯à®• & Order à®šà¯†à®¯à¯à®¯</a></div></section>
<CTA title='Keep your shelves ready for the next customer.' body='Place your wholesale order through EcooBasket.com or speak with our Chennai team.' primary='Order Now' primaryHref='https://www.ecoobasket.com' secondary='Contact Support' secondaryHref='/contact'/>
</main></PageShell>}
